version: '3.1'
networks:
  main:
services:
  redboxportal:
    image: qcifengineering/redbox-portal
    ports:
       - "1500:1500"
    volumes:
       - "../../:/opt/redbox-portal/node_modules/@researchdatabox/redbox-hook-terraform"
       - "./package-gcp.json:/opt/redbox-portal/package.json"
       # If you're not developing redbox-hook-terraform-gcp, comment out the line below
       - "../../../redbox-hook-terraform-gcp:/opt/redbox-portal/node_modules/@researchdatabox/redbox-hook-terraform-gcp"
       - "../../sailsWorkingDir/tmp:/opt/redbox-portal/.tmp"
       # If you're not interested in making changes to the core while developing this plugin, comment out below
       - "../../../redbox-portal/api:/opt/redbox-portal/api"
    expose:
       - "1500"
    environment:
      - NODE_ENV=docker
      - sails_log__level=verbose
      - PORT=1500
      - sails_redbox__apiKey=c8e844fc-8550-497f-b970-7900ec8741ca
      - sails_record__baseUrl__redbox=http://redbox:9000/redbox
      - sails_record__baseUrl__mint=http://demo.redboxresearchdata.com.au/mint
    # Put your sensitive stuff in this environment variable file
    env_file:
      - ../../../temp/gcp.env
    networks:
     main:
       aliases:
         - rbportal
    entrypoint: /bin/bash -c "cd /opt/redbox-portal; node app.js;"
  mongodb:
    image: mvertes/alpine-mongo:latest
    networks:
      main:
        aliases:
          - mongodb
    ports:
       - "27017:27017"
  redbox:
    image: qcifengineering/redbox:2.x
    expose:
       - "9000"
    environment:
      - RB_API_KEY=c8e844fc-8550-497f-b970-7900ec8741ca
    networks:
      main:
        aliases:
          - redbox
    ports:
       - "9000:9000"
